### ISSUE TITLE
必须保存每一个版本的.apk .R .mapping文件吗

### ISSUE THREAD

**Issue by shineM** [BuglyDevTeam/Bugly-Android-Demo#10]
直接根据版本tag代码生成的文件不能匹配上

**Comment by devilWwj** [comment]
只需要保存你每次发版的apk、R、mapping的文件，尽量不要check tag来重新生成基线版本，避免因为环境一些因素导致文件变更。

**Comment by shineM** [comment]
基于check tag生成的patch应该是100%不能成功的，既然这样只能保存每次上线的版本了。Anyway，thanks very much!
