### ISSUE TITLE
横屏模式下更新按钮看不到

### ISSUE THREAD

**Issue by jp1017** [BuglyDevTeam/Bugly-Android-Demo#11]
![device-2017-03-17-110759](https://cloud.githubusercontent.com/assets/7868514/24027383/1f05bca6-0b02-11e7-8df9-f74759a6d00a.png)

**Comment by devilWwj** [comment]
这个问题争取下个版本修复。

**Comment by jp1017** [comment]
SDK v1.2.5 works well. :smile:
