### ISSUE TITLE
tinkerId is not set!!!

### ISSUE THREAD

**Issue by chenjiayulove** [BuglyDevTeam/Bugly-Android-Demo#118]
编译异常

#### Tinker版本
'com.tencent.tinker:tinker-android-lib:1.9.1' 

#### gradle版本
 4.6

#### 系统
 Windows 

#### 堆栈/日志

Cause: tinkerId is not set!!!

设置tinkerId的值不行
tinkerId的值怎么获取    不是设置代码的versionName吗

使用这个autoGenerateTinkerId = true  也不行

我是刚集成  准备编译打基准包出现问题

**Comment by wjbd** [comment]
请查看enable是不是设置为false，设置为false之后就会提示这个

**Comment by chenjiayulove** [comment]
没有啊    是设置为true   不知道什么原因  现在在拿demo测试  生成补丁包时报错这个   有遇到过吗

**Comment by chenjiayulove** [comment]
* What went wrong:
Execution failed for task ':app:tinkerPatchRelease'.
> Could not resolve all files for configuration ':app:sevenZipToolsLocator'.
   > Could not download SevenZip-windows-x86_64.exe (com.tencent.mm:SevenZip:1.1.10)
      > Could not get resource 'https://jcenter.bintray.com/com/tencent/mm/SevenZip/1.1.10/SevenZip-1.1.10-windows-x86_64.exe'.
         > Could not GET 'https://jcenter.bintray.com/com/tencent/mm/SevenZip/1.1.10/SevenZip-1.1.10-windows-x86_64.exe'.
            > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/143.204.31.93, d29vzk4ow07wi7.cloudfront.net/143.204.31.21, d29vzk4ow07wi7.cloudfront.net/143.204.31.220, d29vzk4ow07wi7.cloudfront.net/143.204.31.120] failed: Read timed out

**Comment by chenjiayulove** [comment]
按照文档步骤不知道哪里出错会提示上述信息   一直没解决   现在是直接跑demo   拿demo的来用不会出现这问题

**Comment by wjbd** [comment]
请查看enable是不是设置为false，设置为false之后就会提示这个

**Comment by chenjiayulove** [comment]
设了没用

**Comment by chenjiayulove** [comment]
是设为true

**Comment by wjbd** [comment]
你不是都把这个issue给关闭了，还发啊，再说了，你也不贴你错误的代码，怎么看的出来？
