### ISSUE TITLE
bugly升级sdk在android8.0的设备上 app 无法正常升级更新

### ISSUE THREAD

**Issue by yuqirong** [BuglyDevTeam/Bugly-Android-Demo#125]
#### 异常类型
app运行时异常

#### 手机型号
小米 8 SE

#### 手机系统版本
Android 8.0

#### Tinker版本
1.9.9

#### gradle版本
3.2.1

#### 复现路径
bugly升级sdk在android8.0的设备上 app 无法正常升级更新，会出现下载完成无法自动跳转到安装界面的问题，就一直在重复下载apk包，这个bug什么时候可以修复？

**Comment by zhhp1121** [comment]
> #### 异常类型
> app运行时异常
> 
> #### 手机型号
> 小米 8 SE
> 
> #### 手机系统版本
> Android 8.0
> 
> #### Tinker版本
> 1.9.9
> 
> #### gradle版本
> 3.2.1
> 
> #### 复现路径
> bugly升级sdk在android8.0的设备上 app 无法正常升级更新，会出现下载完成无法自动跳转到安装界面的问题，就一直在重复下载apk包，这个bug什么时候可以修复？

解决办法：
一、compileSdkVersion
targetSdkVersion
配置小于26
例如:
compileSdkVersion = 25
targetSdkVersion = 25
二、如果要使用>=26，例如：
compileSdkVersion = 26
targetSdkVersion = 26
需要等待新版本sdk的发布，目前还在内部测试中。

**Comment by zhhp1121** [comment]
> #### 异常类型
> app运行时异常
> 
> #### 手机型号
> 小米 8 SE
> 
> #### 手机系统版本
> Android 8.0
> 
> #### Tinker版本
> 1.9.9
> 
> #### gradle版本
> 3.2.1
> 
> #### 复现路径
> bugly升级sdk在android8.0的设备上 app 无法正常升级更新，会出现下载完成无法自动跳转到安装界面的问题，就一直在重复下载apk包，这个bug什么时候可以修复？

https://bugly.qq.com/docs/release-notes/release-android-beta/?v=20190108103135  1.3.7版本已经修复

**Comment by yuqirong** [comment]
@zhhp1121 好的 谢谢 已经更新到最新版
