### ISSUE TITLE
有计划适配androidx吗？

### ISSUE THREAD

**Issue by crazecoder** [BuglyDevTeam/Bugly-Android-Demo#128]

**Comment by zhhp1121** [comment]
> #### 异常类型
> #### 手机型号
> #### 手机系统版本
> #### Tinker版本
> #### gradle版本
> #### 系统
> #### 堆栈/日志
> #### 复现路径

后面版本迭代会考虑

**Comment by crazecoder** [comment]
希望能够尽快适配，不然和androidx的库一起使用很麻烦

**Comment by ab503044120** [comment]
> 希望能够尽快适配，不然和androidx的库一起使用很麻烦

好像和androidx一起bug就不会上报了,貌似是UncaughtExceptionHandler没替换成功

**Comment by crazecoder** [comment]
@ab503044120 没有遇到，都可以正常上报，唯一的问题是应用更新

**Comment by pumatus** [comment]
尽快适配一下呗～～～～

**Comment by keepgoodfeeling** [comment]
请适配androidx
