### ISSUE TITLE
enable 设置为 false 时, tinkerId is not set!!!

### ISSUE THREAD

**Issue by jp1017** [BuglyDevTeam/Bugly-Android-Demo#13]
### 1. tinkerSupport

```
tinkerSupport {
    // 开启tinker-support插件，默认值true
    enable = false
    ......
    tinkerId = '6666'
}
```

### 2. compile Error

![20170323140525](https://cloud.githubusercontent.com/assets/7868514/24234184/dba6946a-0fd1-11e7-8748-7b88231067f7.png)

**Comment by jp1017** [comment]
刚发现 `tinkerPatch` 里面也有配置 `tinkerId`, 
也就是说: `tinkerId` 是必须设置的参数, 无论 `enable` 开启与否？是这样吗。

**Comment by devilWwj** [comment]
是这样的，我们插件内部会apply tinker的插件，如果只关闭我们的插件还不够，还需要关闭tinker的插件，可以设置tinkerPatch的tinkerEnable = false试下。不过这个点可以优化下

**Comment by devilWwj** [comment]
因为插件存在一个依赖关系，如果想彻底关掉tinker的插件，还是需要在tinkerPatch中设置tinkerEnable = false。

**Comment by jksld** [comment]
> 是这样的，我们插件内部会apply tinker的插件，如果只关闭我们的插件还不够，还需要关闭tinker的插件，可以设置tinkerPatch的tinkerEnable = false试下。不过这个点可以优化下

建议更新下文档中心的常见问题

Q: 日常调试需要使用instant run，怎么关闭tinker

A：这里分两种情况:

使用反射Application方式接入：可以直接在build.gradle中将apply from: 'tinker-support.gradle'注释掉。

改造Application方式接入：先将tinkerSupport中overrideTinkerPatchConfiguration设置为false 修改成将tinkerSupport中enable设置为false。
