### ISSUE TITLE
tinker-support插件问题

### ISSUE THREAD

**Issue by feer921** [BuglyDevTeam/Bugly-Android-Demo#161]
// tinkersupport插件(1.0.3以上无须再配置tinker插件）
//        classpath "com.tencent.bugly:tinker-support:1.1.5"

不是说，不需要配置插件了吗？？，注释掉后，压根编译通不过：

ERROR: Could not find method tinkerSupport() for arguments [tinker_support_azsie5i03cllfy32dt4dcnqnm$_run_closure1@75dc6e9c] on project ':app' of type org.gradle.api.Project.

**Comment by zhhp1121** [comment]
> // tinkersupport插件(1.0.3以上无须再配置tinker插件）
> // classpath "com.tencent.bugly:tinker-support:1.1.5"
> 
> 不是说，不需要配置插件了吗？？，注释掉后，压根编译通不过：
> 
> ERROR: Could not find method tinkerSupport() for arguments [tinker_support_azsie5i03cllfy32dt4dcnqnm$_run_closure1@75dc6e9c] on project ':app' of type org.gradle.api.Project.

注意：自tinkersupport 1.0.3版本起无需再配tinker插件的classpath。tinker support插件不是tinker插件。这里的意思是需要配置tinker support插件，不用再配置tinker插件。
