### ISSUE TITLE
后台统计问题

### ISSUE THREAD

**Issue by laobie** [BuglyDevTeam/Bugly-Android-Demo#2]
您好，我这边在使用热更新服务时，补丁确实应用成功了，但是后台统计一直显示激活数是 0 。
![image](https://cloud.githubusercontent.com/assets/7184320/20999326/ce7cbc0e-bd4e-11e6-8cb8-74f92f1e5362.png)
上面是补丁日志截图，结果确实是成功了。

**Comment by devilWwj** [comment]
你好，这个问题是我们导致的，下个版本我们会修复这个问题。

**Comment by laobie** [comment]
@devilWwj OK，预计什么时候发布新版本呢？

**Comment by devilWwj** [comment]
下周我们会发个新版本

**Comment by laobie** [comment]
@devilWwj 好的 谢谢~

**Comment by 24suixinsuoyu** [comment]
我也遇到这个问题了~

**Comment by laobie** [comment]
@24suixinsuoyu 等更新吧

**Comment by devilWwj** [comment]
https://bugly.qq.com/v2/sdkDownload 1.2.1版本已经修复这个问题

**Comment by laobie** [comment]
@devilWwj 测试了 1.2.1 版本 已经修复，能统计到激活数量了。
