### ISSUE TITLE
谷歌play上使用Bugly被下架了

### ISSUE THREAD

**Issue by Gennki** [BuglyDevTeam/Bugly-Android-Demo#207]

**Comment by jiao808813** [comment]
同样被下架了，真是服了，希望官方尽快解决

**Comment by tqlmorepassion** [comment]
+1

**Comment by jicwiiaaa** [comment]
bugly这边会有no-op的方案吗，最好是enableProxyApplication = true情况下的适配，ApplicationLike对于成熟项目侵入性有点大

**Comment by Qunter** [comment]
请问一下你们下架了是单集成bugly还是集成了bugly和tinker? @Gennki @jiao808813 @tqlmorepassion

**Comment by jiao808813** [comment]
> 请问一下你们下架了是单集成bugly还是集成了bugly和tinker? @Gennki @jiao808813 @tqlmorepassion

如今又因为版本更新不是来自Google Play的问题下架了，看来谷歌市场对Bugly全面封杀了

**Comment by tqlmorepassion** [comment]
今天的bugly公众号推送了解决方案啊，别用升级sdk和tinker就可以。


---原始邮件---
发件人: &quot;jiao808813&quot;<notifications@github.com&gt;
发送时间: 2020年5月8日(周五) 中午11:27
收件人: &quot;BuglyDevTeam/Bugly-Android-Demo&quot;<Bugly-Android-Demo@noreply.github.com&gt;;
抄送: &quot;Mention&quot;<mention@noreply.github.com&gt;;&quot;tql&quot;<tqlmorepassion@foxmail.com&gt;;
主题: Re: [BuglyDevTeam/Bugly-Android-Demo] 谷歌play上使用Bugly被下架了 (#207)




  
请问一下你们下架了是单集成bugly还是集成了bugly和tinker? @Gennki @jiao808813 @tqlmorepassion
  
如今又因为版本更新不是来自Google Play的问题下架了，看来谷歌市场对Bugly全面封杀了
 
&mdash;

**Comment by Qunter** [comment]
我们现在是只用了bugly,没有接tinker,也没有被下架,只是看到这段时间陆续有app提到这个事,担心自己会不会有问题.....那看来大家都是因为热更之类的更新的问题或者是接入了tinker被下架了,感谢各位的回复!

**Comment by Gennki** [comment]
确实是bugly加上tinker被下架的，只是bugly的话没问题

**Comment by jiao808813** [comment]
我现在应用被暂停了，只能更改包名和应用名重新提交新的APP了，可恶

**Comment by SilenceBurst** [comment]
> 我现在应用被暂停了，只能更改包名和应用名重新提交新的APP了，可恶

兄弟，我们也遇到了，方便交流一下吗 请教几个问题 qq 3328019207

**Comment by tqlmorepassion** [comment]
申诉


---原始邮件---
发件人: &quot;尚尚&quot;<notifications@github.com&gt;
发送时间: 2020年5月18日(周一) 中午12:27
收件人: &quot;BuglyDevTeam/Bugly-Android-Demo&quot;<Bugly-Android-Demo@noreply.github.com&gt;;
抄送: &quot;Mention&quot;<mention@noreply.github.com&gt;;&quot;tql&quot;<tqlmorepassion@foxmail.com&gt;;
主题: Re: [BuglyDevTeam/Bugly-Android-Demo] 谷歌play上使用Bugly被下架了 (#207)




  
我现在应用被暂停了，只能更改包名和应用名重新提交新的APP了，可恶
  
兄弟，我们也遇到了，方便交流一下吗 请教几个问题 qq 3328019207
 
&mdash;

**Comment by SilenceBurst** [comment]
> 申诉

我们申诉了还没得到结果 不知道结果会怎样，已经准备打新包了
你们当时申诉成功了吗？麻烦分享下经验给大家 应该很多人中枪

**Comment by tqlmorepassion** [comment]
成功了啊，你要定位问题，我们之前被暂停，不是因为bugly哈，只是用了应用内更新被下架了一次。后面因为第三方框架有x5，导致被暂停，申诉之后，重新上架了。以后就需要更加注意了，美国疫情严重，可能需要等一下，申诉描述可以诚恳一点，希望还是很大的。


---原始邮件---
发件人: &quot;尚尚&quot;<notifications@github.com&gt;
发送时间: 2020年5月18日(周一) 中午12:47
收件人: &quot;BuglyDevTeam/Bugly-Android-Demo&quot;<Bugly-Android-Demo@noreply.github.com&gt;;
抄送: &quot;Mention&quot;<mention@noreply.github.com&gt;;&quot;tql&quot;<tqlmorepassion@foxmail.com&gt;;
主题: Re: [BuglyDevTeam/Bugly-Android-Demo] 谷歌play上使用Bugly被下架了 (#207)




  
申诉
  
我们申诉了还没得到结果 不知道结果会怎样，已经准备打新包了
 你们当时申诉成功了吗？麻烦分享下经验给大家 应该很多人中枪
 
&mdash;

**Comment by jiao808813** [comment]
> > 我现在应用被暂停了，只能更改包名和应用名重新提交新的APP了，可恶
> 
> 兄弟，我们也遇到了，方便交流一下吗 请教几个问题 qq 3328019207

上周已申诉成功，可以重新发布了

**Comment by SilenceBurst** [comment]
> > > 我现在应用被暂停了，只能更改包名和应用名重新提交新的APP了，可恶
> > 
> > 
> > 兄弟，我们也遇到了，方便交流一下吗 请教几个问题 qq 3328019207
> 
> 上周已申诉成功，可以重新发布了

你们申诉措辞大致怎么讲的，方便借鉴一下吗？我们提交了申诉，已经一周了，还没结果 很担心

**Comment by SilenceBurst** [comment]
> 成功了啊，你要定位问题，我们之前被暂停，不是因为bugly哈，只是用了应用内更新被下架了一次。后面因为第三方框架有x5，导致被暂停，申诉之后，重新上架了。以后就需要更加注意了，美国疫情严重，可能需要等一下，申诉描述可以诚恳一点，希望还是很大的。
> […](#)
> ---原始邮件--- 发件人: &quot;尚尚&quot;<notifications@github.com&gt; 发送时间: 2020年5月18日(周一) 中午12:47 收件人: &quot;BuglyDevTeam/Bugly-Android-Demo&quot;<Bugly-Android-Demo@noreply.github.com&gt;; 抄送: &quot;Mention&quot;<mention@noreply.github.com&gt;;&quot;tql&quot;<tqlmorepassion@foxmail.com&gt;; 主题: Re: [BuglyDevTeam/Bugly-Android-Demo] 谷歌play上使用Bugly被下架了 (#207) 申诉 我们申诉了还没得到结果 不知道结果会怎样，已经准备打新包了 你们当时申诉成功了吗？麻烦分享下经验给大家 应该很多人中枪 &mdash; You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

谢谢了 老铁
