### ISSUE TITLE
游戏APK中的SDK部分，如何用Bugly 来实现热修复

### ISSUE THREAD

**Issue by misty-rain** [BuglyDevTeam/Bugly-Android-Demo#22]
#### Tinker版本

1.7.11

#### gradle版本

3.3

#### 系统

安卓

#### 描述
您好，游戏的APK包，是由公司独立开发的windows版本 基于C# 写的 打包工具，勾选渠道SDK来生成的，请问在这种场景下，如何用Bugly实现SDK部分的热修复？

**Comment by devilWwj** [comment]
只针对Java代码进行热更新
