### ISSUE TITLE
android10 补丁下载成功, 无法安装激活, 提示tinker_classN.odex is not exist

### ISSUE THREAD

**Issue by AweiHuang** [BuglyDevTeam/Bugly-Android-Demo#227]
#### 手机型号
华为mate30. 三星Galaxy S9+

#### 手机系统版本
android 10

#### Tinker版本
com.tencent.tinker:tinker-android-lib:1.9.9

#### gradle版本
 dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0'
        classpath "com.tencent.bugly:tinker-support:latest.release"
    }
distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip

#### 堆栈/日志
E/Tinker.DexDiffPatchInternal: parallel dex optimizer file tinker_classN.odex is not exist

#### 复现路径
公司所有android10手机均无法安装补丁成功, 其他安卓版本正常.

**Comment by yuanhonglie** [comment]
我也遇到这个问题了，目前发现基于relase版本的补丁包在华为的Android10机型上热修复失效，debug版本没有问题，Android10的虚拟机也没有问题。希望有人能解答一下，谢谢！

**Comment by taojr95** [comment]
文档里的版本不是最新的 demo里的没问题

**Comment by AweiHuang** [comment]
谢谢, 之前是按照文档上说明来配置的, 现在按照demo里面的版本号修改了下, android 10手机可以安装成功了.

**Comment by lurongshuang** [comment]
我去试试！！！！！

**Comment by Dingzihao** [comment]
> 谢谢, 之前是按照文档上说明来配置的, 现在按照demo里面的版本号修改了下, android 10手机可以安装成功了.

文档里面的不行。换成demo里面的确实可以了。

**Comment by 84wangmou** [comment]
demo地址可以给我发一下吗
