### ISSUE TITLE
kotlin下，enableProxyApplication = true 时异常

### ISSUE THREAD

**Issue by vihuela** [BuglyDevTeam/Bugly-Android-Demo#23]
#### 异常类型

编译异常

#### Tinker版本

1.7.11

#### gradle版本

4.1/3.3

#### 系统

win10

#### 堆栈/日志

Error:Execution failed for task ':app:tinkerSupportProcessDebugManifest'.
> java.io.FileNotFoundException: D:\code\private\uooconline4Android\app\src\main\java\uooconline\com\education\App.java (系统找不到指定的文件。)

#### 复现路径

这个问题和
[tinker issue](https://github.com/Tencent/tinker/issues/475)描述的一致，
kotlin下，设置enableProxyApplication = true会出现，我现在暂时使用替换application来实现，但是使用了替换application之后，在tinker关闭时，因为application已经经过改造，所以api 21下时需要也需要手动multiDexKeepProguard，所以如果这个问题可以解决就完美了

**Comment by wangcc0909** [comment]
使用kotlin,as3.0版本的时候出现Error:Could not get unknown property 'apkVariantData' for object of type com.android.build.gradle.internal.api.ApplicationVariantImpl.
老铁  这个问题怎么解决? tinker那边都更新到1.9.1了

**Comment by vihuela** [comment]
别急老铁，我解决了，
在defaultConfig标签里，加入：multiDexKeepProguard file('multiDexKeep.pro')
内容如下：
# 屏蔽tinker时，因为使用了改造application的方式接入tinker，所以仍然需要keep主放进main dex处理

#tinker multidex keep patterns:
-keep public class * implements com.tencent.tinker.loader.app.ApplicationLifeCycle {
    <init>(...);
    void onBaseContextAttached(android.content.Context);
}

-keep public class * extends com.tencent.tinker.loader.TinkerLoader {
    <init>(...);
}

-keep public class * extends android.app.Application {
     <init>();
     void attachBaseContext(android.content.Context);
}

-keep class com.tencent.tinker.loader.TinkerTestAndroidNClassLoader {
    <init>(...);
}

#your dex.loader patterns here
-keep class com.tencent.tinker.loader.** {
    <init>(...);
}

-keep class uooconline.com.education.utils.tinker.ProxyApplication {
    <init>(...);
}

**Comment by wangcc0909** [comment]
非常感谢,老铁,使用新版本的插件解决了这个问题

**Comment by devilWwj** [comment]
解决来就好
