### ISSUE TITLE
在tinker-support.gradle里面设置了，def baseApkDir 与生成的目录不对

### ISSUE THREAD

**Issue by xiangxm** [BuglyDevTeam/Bugly-Android-Demo#25]
#### gradle版本
2.3.3

#### 系统
windows

想咨询一下，在tinker-support.gradle里面设置了，def baseApkDir = "app-1011-170919"  但是每次编译出来的目录，却是 app\build\bakApk\app-0919-10-12-31

这里的app-0919-10-12-31 和 app-1011-170919 不对等，是哪里配置有问题吗？

**Comment by MaSiYuan** [comment]
我也遇到这个问题了，请问你是怎么解决的？谢谢。

**Comment by devilWwj** [comment]
你们理解错了，def baseApkDir = "app-1011-170919"这个是打补丁的时候才需要配的，先打基准包，然后再打补丁包
