### ISSUE TITLE
热更新没生效

### ISSUE THREAD

**Issue by 09xuanjian** [BuglyDevTeam/Bugly-Android-Demo#3]
按照文档和demo ,配置了bugly的热更新，然后在后台发布了热更新包。显示下发和激活都有了，但是对于的改动的地方却没有生效。请问有什么可能会造成这种情况？

**Comment by devilWwj** [comment]
你好，下发和激活都有事件上报说明补丁已经合成成功了，没有生效是不是配置上的问题？可以将对应的log和tinker打patch的log发给我们开发同事，或者直接回复此条issue。

**Comment by 09xuanjian** [comment]
已经找到原因，因为项目的原因，修改了一下Gradle的一些配置，导致前后两次对比的包，解压后都放在了同一个文件夹目录下。一对比，就发现没有什么更新的。

**Comment by shaozf** [comment]
Analyze old and new apk files:
old apk: app-_100100101-debug-2017-01-11-11-18.apk, size=12103882, md5=f525b438d1f1837e3c612b0ade7f869c
new apk: app-_100100101-debug.apk, size=12103882, md5=f525b438d1f1837e3c612b0ade7f869c

UnZipping apk to C:\Users\Administrator\Desktop\Projects\tinker_demo\app\build\outputs\tinkerPatch\_100100101\debug\app-_100100101-debug-2017-01-11-11-18
UnZipping apk to C:\Users\Administrator\Desktop\Projects\tinker_demo\app\build\outputs\tinkerPatch\_100100101\debug\app-_100100101-debug
Check for loader classes in dex: classes.dex
Check for loader classes in dex: classes2.dex
No dexes were changed, nothing needs to be done next.
Generate unsigned apk: patch_unsigned.apk
Signing apk: patch_signed.apk
Signing key algorithm is SHA1withRSA
Try use 7za to compress the patch file: patch_signed_7zip.apk, will cost much more time
Current 7za path:C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\com.tencent.mm\SevenZip\1.1.10\4786999cf29d8e3b0c39a80359b5127bda36132a\SevenZip-1.1.10-windows-x86_64.exe
Result: final signed patch result: C:\Users\Administrator\Desktop\Projects\tinker_demo\app\build\outputs\tinkerPatch\_100100101\debug\patch_signed.apk, size=1710
Result: final signed with 7zip patch result: C:\Users\Administrator\Desktop\Projects\tinker_demo\app\build\outputs\tinkerPatch\_100100101\debug\patch_signed_7zip.apk, size=2047
Warning: patch_signed_7zip.apk is bigger than patch_signed.apk 337 byte, you should choose patch_signed.apk at these time!
Tinker patch done, total time cost: 6.538000s
Tinker patch done, you can go to file to find the output C:\Users\Administrator\Desktop\Projects\tinker_demo\app\build\outputs/tinkerPatch/_100100101/debug

**Comment by shaozf** [comment]
这是什么问题？

**Comment by shaozf** [comment]
已经做了修改但是还是获取不到修改的内容。提示没有变化
