### ISSUE TITLE
抱歉,上传过程中出现异常,请尝试重新上传或者联系客服。

### ISSUE THREAD

**Issue by wang2793312458** [BuglyDevTeam/Bugly-Android-Demo#303]
bugly 发布新升级，上传不了apk包

**Comment by PeakWang001** [comment]
一样的 3月20号发现的目前还是有问题  你联系到官方了么

**Comment by MrPsw** [comment]
一样上传不了新版本，{"status":500,"message":"unknown error","errorCode":100001}

**Comment by zhizhi1hao** [comment]
我也遇到了 不过现在可以了

**Comment by PeakWang001** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BuglyDevTeam/Bugly-Android-Demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月22日(星期一) 下午5:14
***@***.***&gt;;
抄送:&nbsp;"瓅.     ***@***.******@***.***&gt;;
主题:&nbsp;Re: [BuglyDevTeam/Bugly-Android-Demo] 抱歉,上传过程中出现异常,请尝试重新上传或者联系客服。 (#303)





 
我也遇到了 不过现在可以了

**Comment by taylorzhangyx** [comment]
后端服务19号出现异常，后端工程师已处理并与今天下午恢复。
