### ISSUE TITLE
bugly上传apk出现异常

### ISSUE THREAD

**Issue by PeakWang001** [BuglyDevTeam/Bugly-Android-Demo#304]
抱歉,上传过程中出现异常,请尝试重新上传或者联系客服。
{"status":500,"message":"unknown error","errorCode":100001}

**Comment by lxgogogo** [comment]
我也是 今天一样上传不了，还联系不到官方

**Comment by zhizhi1hao** [comment]
我今天也遇到了 不过现在可以了

**Comment by taylorzhangyx** [comment]
#303
