### ISSUE TITLE
自定义输出apk名字时报错

### ISSUE THREAD

**Issue by AndyAls** [BuglyDevTeam/Bugly-Android-Demo#32]
bugly热修复输出的apk名字是自定义的 比如系统生成的是app_debug.apk  现在自定义输出的名字是app_debug_v.1.2.3.apk  打补丁时他默认找的是app_debug.apk  这个需要怎么解决啊

具体错误
`Error:Execution failed for task ':app:tinkerPatchXiaomiRelease'.
> old apk C:\Users\shuai.li13\Desktop\Bugly-Android-Demo-master\BuglyHotfixEasyDemo\app\build\bakApk/app-1109-11-07-07/xiaomi/app-xiaomi-release.apk is not exist, you must set the correct old apk value!`

**Comment by AndyAls** [comment]
有老哥能解决 方便加一下微信具体聊聊 1973328389

**Comment by AndyAls** [comment]
官方回复 ,不支持自定义输出apk名字,所以打基准包时把自定义输出包名的相关代码注释掉

**Comment by hloong** [comment]
正准备问这个问题的，建议官方文档应该要注明不支持自定义输出apk
