### ISSUE TITLE
异常的权限使用方式 android.permission.READ_LOGS

### ISSUE THREAD

**Issue by zx98cv12** [BuglyDevTeam/Bugly-Android-Demo#320]
APP在google paly收到警告：异常的权限使用方式 android.permission.READ_LOGS。请问有什么解决方法嘛？

**Comment by zjrwdl** [comment]
gp不允许的权限请不要添加

> APP在google paly收到警告：异常的权限使用方式 android.permission.READ_LOGS。请问有什么解决方法嘛？
