### ISSUE TITLE
上传了so文件为什么查看崩溃信息还是显示“待上传”？UUID也显示“未知”

### ISSUE THREAD

**Issue by 0right** [BuglyDevTeam/Bugly-Android-Demo#322]
平台：安卓
![image](https://user-images.githubusercontent.com/49156461/123103698-db8bed80-d468-11eb-9ca6-cf9298feacaf.png)

**Comment by lhh-sofy** [comment]
> 平台：安卓
> ![image](https://user-images.githubusercontent.com/49156461/123103698-db8bed80-d468-11eb-9ca6-cf9298feacaf.png)

你好，你这边是通过自动上传的还是手动上传的啊，我这边自动上传的时候，报一下错误:
{"rtcode":40401,"msg":"<html>\n<head><title>401 Unauthorized</title></head>\n<body>\n<h1>401 Unauthorized</h1>\n<p /><hr />\n<small>\nResin/4.0.48\nServer: 'app-0'\n</small>\n</body></html>\n"}

**Comment by 0right** [comment]
> > 平台：安卓
> > ![image](https://user-images.githubusercontent.com/49156461/123103698-db8bed80-d468-11eb-9ca6-cf9298feacaf.png)
> 
> 你好，你这边是通过自动上传的还是手动上传的啊，我这边自动上传的时候，报一下错误:
> {"rtcode":40401,"msg":"\n<title>401 Unauthorized</title>\n\n
> 
> # 401 Unauthorized
> \n
> \n\nResin/4.0.48\nServer: 'app-0'\n\n\n"}

我是手动上传的，没试过自动上传所以也不太清楚( •︠ˍ•︡ )

**Comment by zjrwdl** [comment]
https://bugly.qq.com/docs/release-notes/release-android-symboltool/?v=20210625162948
麻烦下载最新符号表工具上传
