### ISSUE TITLE
supportHotplugComponent 属性无法设置

### ISSUE THREAD

**Issue by ck-snow** [BuglyDevTeam/Bugly-Android-Demo#35]
#### 异常类型

添加tinker-support.gradle文件时，sysc后出现Error:Could not set unknown property 'supportHotplugComponent' for object of type com.tencent.bugly.build.gradle.TinkerSupportExtension.。意思是无法为TinkerSupportExtension设置supportHotplugComponent属性，将次行注释后，编译可以通过

#### Tinker版本
1.0.8

#### gradle版本
2.14.1

#### 系统
win10

**Comment by devilWwj** [comment]
1.0.8没有这个参数，需要升级版本

**Comment by devilWwj** [comment]
1.0.9版本以上才支持
