### ISSUE TITLE
限制开发设备的时候 不升级 改成所有设备的时候 才更新成功 初始化的时候已经传入为开发设备

### ISSUE THREAD

**Issue by zhang625480** [BuglyDevTeam/Bugly-Android-Demo#38]
发不升级包  限制开发设备的时候 不升级 ，改成所有设备的时候 才更新成功， 初始化的时候已经传入为开发设备

    Bugly.init(this, "7487d41eec", true);

请问这是什么情况？

**Comment by devilWwj** [comment]
第三个参数不是设置开发设备，只是为了打开调试，输出log
