### ISSUE TITLE
能否提供hotfix下mapping.txt与R.txt的具体示例?

### ISSUE THREAD

**Issue by kHRYSTAL** [BuglyDevTeam/Bugly-Android-Demo#4]
不了解写法 谢谢

**Comment by devilWwj** [comment]
你好，按照我们demo的build.gradle方式配置，如果是release模式会在build目录下生成bakapk目录，会生成对应的mapping文件和R.txt文件。只需要将对应的文件名配置即可。

**Comment by kHRYSTAL** [comment]
@devilWwj thx
