### ISSUE TITLE
补丁包无法发布到bugly后台

### ISSUE THREAD

**Issue by codeccc** [BuglyDevTeam/Bugly-Android-Demo#46]
根据bugly官方教程一步一步编写demo进行接入[{热更新接入指南}](https://bugly.qq.com/docs/user-guide/instruction-manual-android-hotfix/?v=20170912151050#enableproxyapplication-true),在`enableProxyApplication = false 的情况`下到最后生成的补丁包无法发布到bugly后台,提示
`未匹配到可应用补丁包的App版本...` ,此问题必现

**Comment by codeccc** [comment]
建议后续开发这遇到此类情况建议采用 enableProxyApplication = true  的情况下 的方案,enableProxyApplication =false 或是有严重bug

**Comment by devilWwj** [comment]
匹配不到版本问题是补丁没有对应到具体的base tinkerId

**Comment by yq2yizi** [comment]
我操作了好几次,发现后台上传成功的patch版本总是对不上具体的base tinkerId 也不知道什么情况
