### ISSUE TITLE
华为 android 8.0 使用 全量更新 1.3.4 手动更新后点击安装 屏幕一闪，然后就没有了

### ISSUE THREAD

**Issue by xie123** [BuglyDevTeam/Bugly-Android-Demo#47]
华为 android 8.0 使用 全量更新 1.3.4 手动更新后点击安装 屏幕一闪，然后就没有了

#### 异常类型

在此之前有个 警告；FileNotFoundException: /proc/uptime (Permission denied)

#### 手机型号

华为 mate 9 ,华为 p10

#### 手机系统版本
android 8.0 

#### Tinker版本

没有用到

#### gradle版本

gradle 3.0.1

#### 系统

使用android studio 3.0.1

**Comment by xie123** [comment]
如果是 android  文件管理系统 FileNotFoundException 的话（成功配置过的），不应该的，此前成功的。

**Comment by xie123** [comment]
使用 android 8.0 的模拟器 会提示"developer warning for package "xxx" Failed to post notification on channel null "

详情看看:http://blog.csdn.net/rentee/article/details/78303532

**Comment by devilWwj** [comment]
你好，8.0需要配置权限：<uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />
