### ISSUE TITLE
Bugly 控制台处ANR分析未有报告数据 ,求关注

### ISSUE THREAD

**Issue by AXwjg** [BuglyDevTeam/Bugly-Android-Demo#57]
1. 在BuglySDKDemo中的测试ANR CRASH 中手机已经无响应了为什么在控制台中没看到ANR到分析

#### 异常类型
ANR 异常未有分析报告

#### 手机型号
华为MATE - 9

#### 手机系统版本
Android 8.0

#### gradle版本
 3.0.1 

#### 系统
Mac

#### 复现路径
一直点测试ANR CRASH按钮

**Comment by demoNo** [comment]
复议，华为手机都是这个现象。

**Comment by devilWwj** [comment]
你好，ANR在5.0以上版本无读取trace文件权限

**Comment by myuzhuo** [comment]
华为手机都有这种情况么？我的华为荣耀10也无法接收到异常上报，ANR也没有接到上报。三星手机和小米手机是正常的
