### ISSUE TITLE
补丁下载成功,但是应用补丁无反应

### ISSUE THREAD

**Issue by 1wayticket** [BuglyDevTeam/Bugly-Android-Demo#94]
#### 异常类型
 app运行时异常

#### 手机型号
小米8 vivoy83

#### 手机系统版本
 Android8.1

#### Tinker版本
1.9.6

#### gradle版本
3.1.2

#### 系统
win

09-19 17:59:31.832: detective: init log success
09-19 17:59:32.152: detective: onReceiveRegisterResultnull
09-19 17:59:33.194: detective: Beginning load of zpack...
09-19 17:59:33.208: detective: zpack (null) was loaded normally!
09-19 17:59:33.334: detective: 注册成功，设备token为：d1d48499116adce04fdc8c9d3f63e01a02551091
09-19 17:59:35.022: detective: 补丁下载地址https://s.beta.gtimg.com/rdmimg/hot_patch/e45ae71c13/a0b915d1-eff1-4a34-9fe4-7481cf1b7e26.zip
09-19 17:59:35.265: detective: 正在下载 99%
09-19 17:59:35.272: detective: 正在下载 100%
09-19 17:59:35.278: detective: 补丁下载成功/data/user/0/com.mszmapp.detective/app_tmpPatch/tmpPatch.apk

#### provider配置
```
<provider
            android:name="com.tencent.bugly.beta.utils.BuglyFileProvider"
            android:authorities="${applicationId}.fileProvider"
            android:exported="false"
            android:grantUriPermissions="true"
            tools:replace="name,authorities,exported,grantUriPermissions">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"
                tools:replace="name,resource" />
        </provider>
```

 

如上所示,我这样配置provider,但是热更新在6.0版本的nubia手机上就可以更新成功,但是在8,0版本就一直下载成功,然后没有热更新结果回调.
我怀疑是provider配置有问题,但是这都是官网复制过来的,能不能帮忙分析一下,多谢了

**Comment by 1wayticket** [comment]
应该是Android 8.1热更新无效  Android8.0热更新是可以成功的

**Comment by 1wayticket** [comment]
升级tinker 到1.9.8版本可以解决问题

**Comment by shouPol** [comment]
tinker升级到1.9.9之后可以了
 compile 'com.tencent.tinker:tinker-android-lib:1.9.9'
